
# MAIN P10K SETTINGS
## Instant Prompt
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

## Segments
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
  nix_shell
  user
  host
  dir
  vcs

  newline
  prompt_char
)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
  command_execution_time
  status
  background_jobs
  direnv
  virualenv
  time

  newline
)

## Fonts
POWERLEVEL9K_MODE=nerdfont-v3
POWERLEVEL9K_ICON_PADDING=none

## Empty Line before each Prompt
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true

## Prefixes and Suffixes
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=
POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_PREFIX=
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX=
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_SUFFIX=
POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_SUFFIX=
POWERLEVEL9K_MULTILINE_LAST_PROMPT_SUFFIX=

## Filler between L and R
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_CHAR=' '
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_BACKGROUND=
POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_GAP_BACKGROUND=

## Segment Seprataors
POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR='%242F\u2571'
POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR='%242F\u2571'
POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR='\uE0BC' # 
POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR='\uE0BA' # 
POWERLEVEL9K_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL='\uE0BC'
POWERLEVEL9K_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL='\uE0BA'
POWERLEVEL9K_LEFT_PROMPT_FIRST_SEGMENT_START_SYMBOL=''
POWERLEVEL9K_RIGHT_PROMPT_LAST_SEGMENT_END_SYMBOL=''
POWERLEVEL9K_EMPTY_LINE_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL=

# DIRECTORY
## Setings
POWERLEVEL9K_SHORTEN_DIR_LENGTH=1
POWERLEVEL9K_SHORTEN_STRATEGY="truncate_to_unique"
POWERLEVEL9K_SHORTEN_DELIMITER=
POWERLEVEL9K_DIR_SHOW_WRITABLE=v3
POWERLEVEL9K_LOCK_ICON='⭐'
POWERLEVEL9K_DIR_PATH_HIGHLIGHT_BOLD=true

## Directory substitutions with icons
POWERLEVEL9K_DIR_PACKAGE_FILES=(package.json composer.json)
POWERLEVEL9K_DIR_PATH_SEPARATOR="%F{black} %f"
POWERLEVEL9K_HOME_FOLDER_ABBREVIATION="%F{cyan}󰋜 %f"
POWERLEVEL9K_DIR_PATH_ABSOLUTE_FOREGROUND="white"
POWERLEVEL9K_DIR_PATH_HIGHLIGHT_FOREGROUND="blue"
POWERLEVEL9K_DIR_PATH_HIGHLIGHT_BOLD=true
POWERLEVEL9K_DIR_ANCHOR_FOREGROUND="white"
POWERLEVEL9K_DIR_ANCHOR_BOLD=true

## Don't shorten directories that contain any of these files. They are anchors.
POWERLEVEL9K_DIR_ANCHOR_BOLD=true
POWERLEVEL9K_SHORTEN_FOLDER_MARKER="(${(j:|:)anchor_files})"
local anchor_files=(
  .bzr
  .citc
  .git
  .hg
  .node-version
  .python-version
  .go-version
  .ruby-version
  .lua-version
  .java-version
  .perl-version
  .php-version
  .tool-versions
  .shorten_folder_marker
  .svn
  .terraform
  CVS
  Cargo.toml
  composer.json
  go.mod
  package.json
  stack.yaml
)


# COLOR
# Color & icon settings
POWERLEVEL9K_NIX_SHELL_FOREGROUND='#ffffff' # white
POWERLEVEL9K_NIX_SHELL_BACKGROUND='#7eb4df' # lightblue
POWERLEVEL9K_USER_BACKGROUND='#573fbd'
POWERLEVEL9K_USER_FOREGROUND='#ffffff'
POWERLEVEL9K_USER_ICON="\uF415" # 
POWERLEVEL9K_ROOT_ICON="#"
POWERLEVEL9K_SUDO_ICON=$'\uF09C' # 

POWERLEVEL9K_HOST_BACKGROUND='#332671'
POWERLEVEL9K_HOST_FOREGROUND='#ffffff'
POWERLEVEL9K_DIR_BACKGROUND='#22194b'
POWERLEVEL9K_DIR_FOREGROUND='#ffffff'
POWERLEVEL9K_VCS_BACKGROUND='#22194b'
POWERLEVEL9K_VCS_FOREGROUND='#22EF92'
POWERLEVEL9K_STATUS_OK_BACKGROUND='#22194b'
POWERLEVEL9K_STATUS_OK_FOREGROUND='#22EF92'
POWERLEVEL9K_STATUS_ERROR_BACKGROUND='#22194b'
POWERLEVEL9K_STATUS_ERROR_FOREGROUND='#FF5A74'
POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND='#22194b'
POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND='yellow'
POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND='#22194b'
POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND='red'
POWERLEVEL9K_TIME_BACKGROUND='#22194b'
POWERLEVEL9K_TIME_FOREGROUND='#ffffff'


# Background jobs settings
POWERLEVEL9K_BACKGROUND_JOBS_VERBOSE=false
POWERLEVEL9K_BACKGROUND_JOBS_VISUAL_IDENTIFIER_EXPANSION='${P9K_VISUAL_IDENTIFIER// }'
typeset -g POWERLEVEL9K_BACKGROUND_JOBS_{CONTEXT,FOREGROUND,BACKGROUND}=()
typeset -g POWERLEVEL9K_BACKGROUND_JOBS_VERBOSE_ALWAYS=false
function custom_background_jobs() {
  local jobs=${$(jobs -l | wc -l)// /}
  if [[ $jobs -eq 1 ]]; then
    echo ""
  elif [[ $jobs -gt 1 ]]; then
    echo "$jobs "
  fi
}
POWERLEVEL9K_BACKGROUND_JOBS_CONTENT_EXPANSION='$(custom_background_jobs)'

# VCS settings
POWERLEVEL9K_VCS_CLEAN_FOREGROUND='#22EF92'
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='#FF5A74'
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='#FF5A74'
POWERLEVEL9K_VCS_LOADING_FOREGROUND='#8366fc'
POWERLEVEL9K_VCS_CONFLICTED_FOREGROUND='yellow'
POWERLEVEL9K_VCS_STAGED_FOREGROUND='cyan'
POWERLEVEL9K_VCS_STASH_FOREGROUND='magenta'
POWERLEVEL9K_VCS_INCOMING_CHANGES_FOREGROUND='#22EF92'
POWERLEVEL9K_VCS_OUTGOING_CHANGES_FOREGROUND='#FF5A74'
# POWERLEVEL9K_VCS_COMMIT_ICON='\uF417'
# POWERLEVEL9K_VCS_UNTRACKED_ICON='\uF059'
# POWERLEVEL9K_VCS_UNSTAGED_ICON='\uF06A'
# POWERLEVEL9K_VCS_STAGED_ICON='\uF055'
# POWERLEVEL9K_VCS_INCOMING_CHANGES_ICON='\uF01A'
# POWERLEVEL9K_VCS_OUTGOING_CHANGES_ICON='\uF01B'
# POWERLEVEL9K_VCS_STASH_ICON='\uF01C'
# POWERLEVEL9K_VCS_TAG_ICON='\uF02B'
POWERLEVEL9K_VCS_BRANCH_ICON=" "

# Time settings
POWERLEVEL9K_TIME_FORMAT="%D{%H:%M}"

# Command execution time
POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=0
POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION=2

# Prompt character
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=""
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="❯ " # ↳
POWERLEVEL9K_PROMPT_CHAR_OK_VIINS_FOREGROUND='#8366fc'
POWERLEVEL9K_PROMPT_CHAR_ERROR_VIINS_FOREGROUND='#FF5A74'
POWERLEVEL9K_PROMPT_CHAR_OK_VICMD_FOREGROUND='#22EF92'
POWERLEVEL9K_PROMPT_CHAR_OK_VIINS_CONTENT_EXPANSION='❯'
POWERLEVEL9K_PROMPT_CHAR_ERROR_VIINS_CONTENT_EXPANSION='❯'
POWERLEVEL9K_PROMPT_CHAR_OK_VICMD_CONTENT_EXPANSION='❮'

