require("ibl").setup({
  --char = "|", -- "│",
  --char_list_blankline = { "|", "┊", "┆", "¦"},
  space_char_blankline = " ",
  max_indent_increase = 1,
  --use_treesitter = false,
  show_end = false,
  show_current_context = false,
  --show_current_context_start = true,
  show_trailing_blankline_indent = false,
  context_patterns = {
    "class",
    "function",
    "method",
    "while",
    "do_statement",
    "closure",
    "for",
  },
  viewport_buffer = {
    min = 50,
    max = 600,
  },
  filetype_exclude = {
    "help",
    "terminal",
    "dashboard",
    "startify",
    "alpha",
    "packer",
    "neogitstatus",
    "tsplayground",
    "aerial",
  },
  buftype_exclude = { "terminal" },
})
