// GENERATED by `cargo web gen-api` from the gateway OpenAPI spec.
// Enum variant lists are sourced from Rust enums; do not edit by hand
// and do not retype variant lists in components.

export type EnumValues = Record<string, readonly string[]>;

export const enumValues: EnumValues = {
  "AccessMode": [
    "read",
    "write",
    "read_write"
  ],
  "ApprovalDecision": [
    "approve"
  ],
  "ApprovalMode": [
    "both",
    "out_of_band_required",
    "agent_tool"
  ],
  "ApprovalTimeoutAction": [
    "escalate",
    "cancel",
    "auto_approve"
  ],
  "AuthMode": [
    "api_key",
    "o_auth"
  ],
  "AutonomyLevel": [
    "readonly",
    "supervised",
    "full"
  ],
  "ConditionValueType": [
    "string",
    "number",
    "bool",
    "enum",
    "date_time"
  ],
  "ConfigApiCode": [
    "path_not_found",
    "validation_failed",
    "config_changed_externally",
    "reload_failed",
    "op_not_supported",
    "secret_test_forbidden",
    "value_type_mismatch",
    "required_field_empty",
    "invalid_numeric_range",
    "invalid_format",
    "invalid_enum_variant",
    "dangling_reference",
    "internal_error"
  ],
  "CronShellOutputFormat": [
    "wrapped",
    "raw"
  ],
  "DelegateExecutionMode": [
    "bounded",
    "independent"
  ],
  "DelegationMode": [
    "forbidden",
    "allow"
  ],
  "DiscordReactionScope": [
    "off",
    "own",
    "all"
  ],
  "FilesystemEventKind": [
    "created",
    "modified",
    "deleted",
    "renamed"
  ],
  "FirecrawlMode": [
    "scrape",
    "crawl"
  ],
  "FlowRole": [
    "sequence",
    "dependency",
    "failure",
    "switch",
    "trigger"
  ],
  "GlmEndpoint": [
    "cn",
    "global"
  ],
  "GraphSeverity": [
    "warning",
    "error"
  ],
  "HardwareTransport": [
    "None",
    "Native",
    "Serial",
    "Probe"
  ],
  "KiloEndpoint": [
    "gateway"
  ],
  "LarkReceiveMode": [
    "websocket",
    "webhook"
  ],
  "LineDmPolicy": [
    "open",
    "pairing",
    "allowlist"
  ],
  "LineGroupPolicy": [
    "open",
    "mention",
    "disabled"
  ],
  "LogLlmRequestPayload": [
    "off",
    "redacted",
    "full"
  ],
  "LogPersistence": [
    "none",
    "rolling",
    "full",
    "rotating"
  ],
  "LogToolIo": [
    "off",
    "redacted",
    "full"
  ],
  "MatrixStreamMode": [
    "off",
    "partial",
    "single_message",
    "multi_message"
  ],
  "MattermostListenMode": [
    "polling",
    "websocket"
  ],
  "McpTransport": [
    "stdio",
    "http",
    "sse"
  ],
  "MemoryBackendKind": [
    "none",
    "sqlite",
    "postgres",
    "qdrant",
    "markdown",
    "lucid"
  ],
  "MemoryDedupAction": [
    "reject",
    "merge"
  ],
  "MemoryEvictOrder": [
    "value",
    "oldest"
  ],
  "MinimaxEndpoint": [
    "cn",
    "intl"
  ],
  "MoonshotEndpoint": [
    "cn",
    "intl",
    "code"
  ],
  "NodeKind": [
    "step",
    "trigger"
  ],
  "NodeRunState": [
    "completed",
    "failed",
    "skipped",
    "pending",
    "active"
  ],
  "ObservabilityBackend": [
    "none",
    "log",
    "verbose",
    "prometheus",
    "otel"
  ],
  "OnNoApprover": [
    "deny",
    "inherit-originator"
  ],
  "OtelContentPolicy": [
    "off",
    "redacted",
    "full"
  ],
  "OtpMethod": [
    "totp",
    "pairing",
    "cli-prompt"
  ],
  "OutputModality": [
    "mirror",
    "voice",
    "text"
  ],
  "PinClass": [
    "flow",
    "data"
  ],
  "ProxyScope": [
    "environment",
    "zeroclaw",
    "services"
  ],
  "QwenEndpoint": [
    "cn",
    "intl",
    "us",
    "code"
  ],
  "RuntimeKind": [
    "native",
    "docker",
    "cloudflare"
  ],
  "SearchMode": [
    "bm25",
    "embedding",
    "hybrid"
  ],
  "SkillsPromptInjectionMode": [
    "full",
    "compact"
  ],
  "SlashCommandScope": [
    "global",
    "guild"
  ],
  "SopAdmissionPolicy": [
    "parallel",
    "hold",
    "coalesce",
    "drop"
  ],
  "SopDispatch": [
    "agent_loop",
    "sop",
    "sop_and_agent_loop"
  ],
  "SopExecutionMode": [
    "auto",
    "supervised",
    "step_by_step",
    "priority_based",
    "deterministic"
  ],
  "SopPriority": [
    "low",
    "normal",
    "high",
    "critical"
  ],
  "SopRunStatus": [
    "pending",
    "running",
    "waiting_approval",
    "completed",
    "failed",
    "cancelled",
    "cancel_requested",
    "paused_checkpoint"
  ],
  "SopRunStoreBackend": [
    "sqlite",
    "memory"
  ],
  "SopStepKind": [
    "execute",
    "checkpoint",
    "capability"
  ],
  "StepFailure": [
    "fail"
  ],
  "StepfunEndpoint": [
    "cn",
    "intl"
  ],
  "StreamMode": [
    "off",
    "partial",
    "multi_message"
  ],
  "StreamReasoningMode": [
    "off",
    "status",
    "full"
  ],
  "StreamToolArgumentBase": [
    "none",
    "safe",
    "all"
  ],
  "ThinkingDisplayMode": [
    "off",
    "omitted",
    "updates",
    "summarized"
  ],
  "ThinkingLevel": [
    "off",
    "minimal",
    "low",
    "medium",
    "high",
    "max"
  ],
  "ToolFilterGroupMode": [
    "always",
    "dynamic"
  ],
  "ToolResultImagePolicy": [
    "image_url",
    "omit"
  ],
  "TriggerFieldKind": [
    "text",
    "list",
    "expression"
  ],
  "UpgradeStatusState": [
    "idle",
    "running",
    "done",
    "restarting",
    "failed"
  ],
  "VoiceProvider": [
    "twilio",
    "telnyx",
    "plivo"
  ],
  "WhatsAppChatPolicy": [
    "allowlist",
    "ignore",
    "all"
  ],
  "WhatsAppWebMode": [
    "business",
    "personal"
  ],
  "WireApi": [
    "responses",
    "chat_completions"
  ],
  "ZaiEndpoint": [
    "cn",
    "global"
  ]
};

/** Variant list for a generated string enum, or an empty array. */
export function enumMembers(schema: string): readonly string[] {
  return enumValues[schema] ?? [];
}
