#!/bin/sh

# TODO: research how to bind workspaces across monitors

# number of workspaces
bspc monitor DP-0 -d I II III IV V VI VII VIII IX X
bspc monitor DP-2 -d I II III IV V VI VII VIII IX X

# launch
## keybindings daemon
pgrep -x sxhkd > /dev/null || sxhkd &

## alttab
pgrep -x alttab > /dev/null || alttab -d 1 -t 150x150 -i 64x64 -s 2 -bg '#1a1b26' -fg '#c0caf5' -frame '#573fbd' -bc '#22194b' -font 'xft:FiraCodeNFM-Reg' -b 1 &

# window config
bspc config border_width 0
bspc config window_gap 16
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

# padding outside of window
bspc config top_padding 60
bspc config bottom_padding 60
bspc config left_padding 60
bspc config right_padding 60

# move floating windows
bspc config pointer_action1 move

# resize floating windows
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner

# floating windows
#bspc rule -a vlc desktop='^4' follow=on
#bspc rule -a KeePassXC state=floating center=true rectangle=909x625+0+0
bspc rule -a feh state=floating center=true
#bspc rule -a galculator state=floating
